AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This template creates an EC2 instance in a specified VPC subnet with a security group 
  that allows HTTP and SSH access. The instance is configured to run a static website using Apache.

Parameters:

  VPCParameter:
    Description: Select the VPC where the resources will be created
    Type: AWS::EC2::VPC::Id

  SubnetParameter:
    Description: Select the Subnet where the EC2 instance will be launched
    Type: AWS::EC2::Subnet::Id

  InstanceType:
    Description: Select the instance type for the EC2 instance
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t2.nano

  keyName:
    Description: Name of the key pair to use for SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName


  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64'

#Mappings:
 # RegionMap:
  #  us-east-1:
   #   AMI: ami-05ffe3c48a9991133
    #eu-central-1:
     # AMI: ami-0229b8f55e5178b65

Resources:

  mySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH access to EC2
      VpcId: !Ref VPCParameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MySecurityGroup

  myInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref keyName
      SubnetId: !Ref SubnetParameter
      SecurityGroupIds:
        - !Ref mySG
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Instance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd git
          chmod -R 777 /var/www/html
          cd /var/www/html
          rm -rf /var/www/html/*
          git clone https://github.com/iskilicaslan61/Projects.git
          cp -r Projects/101-kittens-carousel-static-website-ec2/static-web/* .
          rm -rf Projects
          systemctl start httpd
          systemctl enable httpd

Outputs:

  PublicIP:
    Description: URL of the static website
    Value: !Sub 
      - http://${PublicDNS}
      - PublicDNS : !GetAtt myInstance.PublicDnsName   
